version: "2"
languages:
    Python: true
checks:
  argument-count:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 30
exclude_patterns:
    - tests/
